### ISSUE TITLE
Bad class file 

### ISSUE THREAD

**Issue by akarnokd** [mojohaus/animal-sniffer#48] opened 2018-04-20 09:53 UTC
Hi. 

I'm getting a [Bad class file error](https://travis-ci.org/akarnokd/RxJava2_9/jobs/369046344#L544) when compiling and running with Java 9.0.1 on Travis or Running [Java 10.0.1](https://travis-ci.org/akarnokd/RxJava2_9/jobs/369046347#L578). Similarly, it happens with Java 9.0.4 on my local machine.

Versions: 
   ru.vyarus:gradle-animalsniffer-plugin:1.4.3
   animal-sniffer 1.16
   gradle 4.7

```
[Unrecognized error] Bad class file 
c:\...\RxJava2_9\build\classes\java\jmh\io\reactivex\BlockingGetPerf.class
```

[BlockingGetPerf.zip](https://github.com/mojohaus/animal-sniffer/files/1931594/BlockingGetPerf.zip)

This started happening after I upgraded from the plugin version 1.2.0 (which I believe run 1.15).

I know that in theory, Java 9+ have their own sniffer, but the library in question is cross-compiled to many JDK versions and compile targets to make sure both the library and the JDKs are okay.

Please advise.

**Comment by xvik** [comment] 2018-04-20 10:05
Hi

You compile with [target 1.9](https://travis-ci.org/akarnokd/RxJava2_9/jobs/369046344#L521) and checking with [1.6 signatures](https://github.com/akarnokd/RxJava2_9/blob/master/build.gradle#L75). Just use correct signature version (for java 9).

**Comment by akarnokd** [comment] 2018-04-20 10:08
The library is supposed to use Java 6 API only, that's why I use 1.6 signatures and cross compile it onto different targets.

**Comment by xvik** [comment] 2018-04-20 10:10
Then you need to compile with [targetCompatibility= 1.6](https://github.com/akarnokd/RxJava2_9/blob/master/build.gradle#L57).

**Comment by akarnokd** [comment] 2018-04-20 10:11
Using JDK 8u151, target 8, signature 1.6 [passes without an error](https://travis-ci.org/akarnokd/RxJava2_9/jobs/369058338#L739).

**Comment by xvik** [comment] 2018-04-20 10:35
This looks like asm version problem(maybe [317791: Invalid class files generated for large methods (regression introduced in 5.2)](http://asm.ow2.org/history.html)).

I can only suggest to try to manually update asm version, used by plugin:
```groovy
dependencies {
    animalsniffer 'org.codehaus.mojo:animal-sniffer-ant-tasks:1.16'
    animalsniffer 'org.ow2.asm:asm-all:5.1'
}
```
By default, asm version is 5.2, but try lower version (in case if you face 5.2 regression). Or you can try newer verison, but artifact name changed for asm6 (should be simply [asm](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22asm%22) and you will need exclude transitive asm-all first. But I'm not sure animalsniffer will work with asm 6.

Personally I didnt tried to use animalsniffer with java 9 or above and so there is notthing else I can suggest (as gradle plugin author).. if this trick will not help then only animalsniffer developer could help

**Comment by xvik** [comment] 2018-04-20 10:55
Another thought: maybe you don't actually need to check compatibility for jmh tests and use animalsniffer only for main source set:
```groovy
animalsniffer {
    sourceSets = [project.sourceSets.main]
}
```

**Comment by akarnokd** [comment] 2018-04-20 11:52
It is as much of a check for the library components as for the JDK itself. We are participating in the early access program and run our builds against the early-access builds of the JDK. We have found at least one javac bug before and we might have found another one due to a unit test in the project:

```java
public class ObjNullCheck {
    static class A {
        class B {

        }

        B createB() {
            return new B();
        }
    }

    public static void main(String[] args) {
        A a = new A();

        A.B b = a.new B(); // <----- animalsniffer error: java.util.Objects.requireNonNull usage

        System.out.println(b);
    }
}
```

In the code above, when compiled with Java 9 target 8 and checked with signatures@1.6, AnimalSniffer will complain that there is an `Objects.requireNonNull` call on that line. Since the code doesn't reference that class at all, the javac must have inserted that call. The interesting part is that Java 9 target 6 & 9 don't cause this error. Java 8 target 8 also doesn't insert that call and thus no complaints.

I'm just mentioning this as it is not an AnimalSniffer problem but a javac one.

**Comment by olamy** [comment] 2018-08-01 04:30
closing as not a problem of this project.
if something really need to get fixed here please reopen with some details

**Closed by olamy** 2018-08-01 04:30 UTC
